---
title: "CourseProject_607"
author: "Joshua Chu"
date: "9/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

R Markdown was used to author this HTML document using a dataset obtain from
baseball savant (MLB, 2020).

```{r }
# load the required libraries for project
library(dplyr); library(ggplot2); library(cowplot); library(corrplot); library(ggpubr)


# remove variables saved in environment
rm(list = ls())


# load dataset and rename columns
x <- read.csv("stats.csv")
colnames(x) <- c("last_name", "first_name", "year", "player_age", "games", "innings_pitched", "hits", 
                 "single", "double", "triple", "home_run", "strikeouts", "walks", "percent_strikeouts",
                 "percent_walks", "batting_avg", "slg_percent", "on_base_percent", "on_base_plus_slug",
                 "wins", "loss", "quality_starts", "starts", "no_slider", "speed_slider", "spin_slider", 
                 "no_changeup", "speed_changeup", "spin_changeup", "no_curve", "speed_curve", "spin_curve",
                 "no_fastball", "speed_fastball", 'spin_fastball')
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.




## References

Advanced Media, MLB. (2020). Retrieved from https://baseballsavant.mlb.com/leaderboard/custom?year=2019&type=pitcher&filter=&sort=4&sortDir=asc&min=q&selections=xba,xslg,xwoba,xobp,xiso,exit_velocity_avg,launch_angle_avg,barrel_batted_rate,&chart=false&x=xba&y=xba&r=no&chartType=beeswarm. Date Accessed: Sept 27, 2020.

